---
title: "Rworksheet_Esmalla#4b"
author: "Janessa Marie Esmalla"
date: "2023-11-08"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r name, echo = TRUE} 



#1 Using the for loop, create an R script that will display a 5x5 matrix as shown in Figure 1. It must contain vectorA = [1,2,3,4,5] and a 5 x 5 zero matrix.

vec_A <- c(1,2,3,4,5)
zero_matrix <- matrix(0,nrow=5,ncol=5)
matrix_result <- rbind(vec_A,zero_matrix)
print(matrix_result)

#2 Print the string "*" using for() function. The output should be the same as shown in Figure


 


#3 Get an input from the user to print the Fibonacci sequence starting from the 1st input up to 500. Use repeat and break statements. Write the R Scripts and its output.










#4 Import the dataset as shown in Figure 1 you have created previously.



#a. What is the R script for importing an excel or a csv file? Display the first 6 rows of the dataset? Show your codes and its result



#b. Create a subset for gender(female and male). How many observations are there in Male? How about in Female? Write the R scripts and its output.



#5


# data
income <- c(60, 10, 5, 25)

# labels and colors
labels <- c("Food", "Electricity", "Savings", "Miscellaneous")
colors <- c("#9B59B6", "#3498DB", "#2ECC71", "#F1C40F")

# pie chart
pie(income, labels = labels, col = colors)
title(main = "Monthly Expenses of Dela Cruz Family")
```














